### PR TITLE
Fixup quote typos

### PR DESCRIPTION
**Pull request by EddieEldridge**
- Cleaned up as many typos, strange characters, and incomplete sentences as I could.
- Checked the formatting was good with a CSV linter

There were too many entries to go through and double check everything but I think I got most of it. 

Thanks again for your awesome project. I am currently using it in my [Discord bot](https://github.com/EddieEldridge/clank) and I intend to use it to display some nice quotes on my new [site](https://github.com/EddieEldridge/sounds-of-middle-earth).

### CODE REVIEW

**Comment by joshdfuqua** [comment]
@EddieEldridge Did you work on all CSVs or just the quote file?

**Comment by EddieEldridge** [comment]
> @EddieEldridge Did you work on all CSVs or just the quote file?

Hey Josh, I just fixed up the **qoutes.csv** file.

**Comment by joshdfuqua** [comment]
> > @EddieEldridge Did you work on all CSVs or just the quote file?
> 
> Hey Josh, I just fixed up the **qoutes.csv** file.

Awesome, thanks man.  I'm working on the characters file right now.  Just wanted to make sure there weren't going to be any merge conflicts whenever I finished.

**Comment by gitfrosh** [comment]
Thanks so much @EddieEldridge for all your hard work here! 
The changes will go live with the next release. 🚀

**Pull request merged**
