### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Os51**
# What type of PR is this?
- [x] Documentation Update

## Description
Redesign of the LOTR-API Project Starter Page / README.md

### Overview of Changes
- Structural changes to README topics
- Addition of badge.io shields for the repository statistics
- Brief overview of the languages used in the source (per information obtained from developer website)
- Addition of contributors image - embed from contrib.rocks
- Added a Contacts section - shields added and hyperlinked to gitfrosh's Github Profile and a mailto protocol hyperlink for the email address under "Ask me anything".

## Related Tickets & Documents
- #82

Thank you! Please let me know if any additions or removals need to be done.

### CODE REVIEW

**Comment by EddieEldridge** [comment]
Nice work, looks great!

**Comment by MateuszKikmunter** [comment]
Looks really good, thanks! 🙂

**Review by MateuszKikmunter — APPROVED** [review]

**Comment by Os51** [comment]
> image I think it would look nicer if this text was also centered but just my opinion :)

That should be fine to do if preferred 😄 - would you like me to edit it?

**Comment by Os51** [comment]
I've made some changes per https://github.com/gitfrosh/lotr-api/pull/83#issuecomment-1290247323 

Top details now look like: 
PR LOTRAPI_Preview

- Additionally made some code amendments for better readability and removed an unassociated tag that I seem to have missed previously.

Thanks for the feedback and support!

**Review by MateuszKikmunter — APPROVED** [review]
Looks good !

**Comment by EddieEldridge** [comment]
> I've made some changes per [#83 (comment)](https://github.com/gitfrosh/lotr-api/pull/83#issuecomment-1290247323)
Nice work, I like it a lot :)

**Comment by gitfrosh** [comment]
Awesome, thanks for your contribution, @Os51! Your PR will be merged for the next release after #hacktoberfest is done. :)

**Comment by Os51** [comment]
> Awesome, thanks for your contribution, @Os51! Your PR will be merged for the next release after #hacktoberfest is done. :)

Thank you! Been a pleasure :)

**Pull request merged**
