### PR TITLE
Updates dev environment to use docker

### PR DESCRIPTION
**Pull request by iisisrael**
Addresses issue #115

### CODE REVIEW

**Comment by iisisrael** [comment]
Forgot to mention, I've only worked on this in a linux environment.  I'll boot into windows tomorrow and see what I see.

**Comment by MateuszKikmunter** [comment]
Hey @iisisrael , nicely done, but there's a [PR](https://github.com/gitfrosh/lotr-api/pull/116) for TypeScript migration for the backend part, so I'd suggest to wait until it's merged and incorporate TS changes into your PR.

**Comment by iisisrael** [comment]
@MateuszKikmunter I'm not seeing anything that would have to change here.  The TS dependencies are all handled by `npm`, and the docker environment is happily agnostic, I think?  I'll try merging both PRs locally, see what happens.

**Comment by iisisrael** [comment]
This is the only merge that needs to happen:
```
diff --git a/.gitignore b/.gitignore
index 0026ed3..7d0a66a 100644
--- a/.gitignore
+++ b/.gitignore
@@ -8,4 +8,5 @@ docker-compose.yml
 dump
 .DS_Store
 bk
-backend/dist
\ No newline at end of file
+backend/dist
+docker/db
```

Everything builds and runs, though after signing up the backend crashed - nodemon logs aren't very insightful:
```
israel@DESKTOP-N8K5LK1:~/dev/forked/lotr-api$ docker container logs lotr-backend-1

> lotr-api-backend@2.1.0 dev
> nodemon server.ts

[nodemon] 3.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node server.ts`
(node:35) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:35) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Database Connected
LotR backend listening on port 3001!
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by MateuszKikmunter** [comment]
> RE: trial merge of this PR and #116...
> 
> This is the only file merge that needs to happen:
> 
> ```
> diff --git a/.gitignore b/.gitignore
> index 0026ed3..7d0a66a 100644
> --- a/.gitignore
> +++ b/.gitignore
> @@ -8,4 +8,5 @@ docker-compose.yml
>  dump
>  .DS_Store
>  bk
> -backend/dist
> \ No newline at end of file
> +backend/dist
> +docker/db
> ```
> 
> Everything builds and runs, though after signing up the backend crashed - nodemon logs aren't very insightful:
> 
> ```
> israel@DESKTOP-N8K5LK1:~/dev/forked/lotr-api$ docker container logs lotr-backend-1
> 
> > lotr-api-backend@2.1.0 dev
> > nodemon server.ts
> 
> [nodemon] 3.0.2
> [nodemon] to restart at any time, enter `rs`
> [nodemon] watching path(s): *.*
> [nodemon] watching extensions: ts,json
> [nodemon] starting `ts-node server.ts`
> (node:35) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> (node:35) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
> Database Connected
> LotR backend listening on port 3001!
> [nodemon] app crashed - waiting for file changes before starting...
> ```

Then it's not working entirely I'd say. Let's check if the same happens only with TS code. I'll pull your branch when I have some time and will take a look too as I'm curious what's going on there. In the end we could also get rid of redis and watch changes in another way while container is running

**Comment by iisisrael** [comment]
@MateuszKikmunter solved the crashing, Alpine container architecture doesn't support the bcrypt binary execution.

**Comment by MateuszKikmunter** [comment]
> @MateuszKikmunter solved the crashing, Alpine container architecture doesn't support the bcrypt binary execution.

Nice, thanks for looking at it!

**Comment by MateuszKikmunter** [comment]
Looks good to me but @gitfrosh pls take a look too.

**Review by MateuszKikmunter — APPROVED** [review]

**Review by MateuszKikmunter — APPROVED** [review]

**Review by gitfrosh — APPROVED** [review]

**Comment by gitfrosh** [comment]
@iisisrael and @MateuszKikmunter, thanks for this amazing improvement!

**Pull request merged**
